/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/hobbies`; params?: Router.UnknownInputParams; } | { pathname: `/reminders`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(hidden)'}/brainwaker` | `/brainwaker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(hidden)'}/taskling` | `/taskling`; params?: Router.UnknownInputParams; } | { pathname: `${'/(hidden)'}/wins` | `/wins`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Auding-You` | `/Auding-You`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Connect` | `/Connect`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Farm` | `/Farm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Research` | `/Research`; params?: Router.UnknownInputParams; } | { pathname: `/research/indexResearch`; params?: Router.UnknownInputParams; } | { pathname: `/research/searchResearch`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/hobbies`; params?: Router.UnknownOutputParams; } | { pathname: `/reminders`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(hidden)'}/brainwaker` | `/brainwaker`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(hidden)'}/taskling` | `/taskling`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(hidden)'}/wins` | `/wins`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Auding-You` | `/Auding-You`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Connect` | `/Connect`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Farm` | `/Farm`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Research` | `/Research`; params?: Router.UnknownOutputParams; } | { pathname: `/research/indexResearch`; params?: Router.UnknownOutputParams; } | { pathname: `/research/searchResearch`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/hobbies${`?${string}` | `#${string}` | ''}` | `/reminders${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(hidden)'}/brainwaker${`?${string}` | `#${string}` | ''}` | `/brainwaker${`?${string}` | `#${string}` | ''}` | `${'/(hidden)'}/taskling${`?${string}` | `#${string}` | ''}` | `/taskling${`?${string}` | `#${string}` | ''}` | `${'/(hidden)'}/wins${`?${string}` | `#${string}` | ''}` | `/wins${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Auding-You${`?${string}` | `#${string}` | ''}` | `/Auding-You${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Connect${`?${string}` | `#${string}` | ''}` | `/Connect${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Farm${`?${string}` | `#${string}` | ''}` | `/Farm${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Research${`?${string}` | `#${string}` | ''}` | `/Research${`?${string}` | `#${string}` | ''}` | `/research/indexResearch${`?${string}` | `#${string}` | ''}` | `/research/searchResearch${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/hobbies`; params?: Router.UnknownInputParams; } | { pathname: `/reminders`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(hidden)'}/brainwaker` | `/brainwaker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(hidden)'}/taskling` | `/taskling`; params?: Router.UnknownInputParams; } | { pathname: `${'/(hidden)'}/wins` | `/wins`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Auding-You` | `/Auding-You`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Connect` | `/Connect`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Farm` | `/Farm`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Research` | `/Research`; params?: Router.UnknownInputParams; } | { pathname: `/research/indexResearch`; params?: Router.UnknownInputParams; } | { pathname: `/research/searchResearch`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
